/**
 * POST /api/ai/document
 *
 * AI Auto-Documentation endpoint.
 *
 * ┌──────────────────────────────────────────────────────────┐
 * │  🤖  AI PLACEHOLDER  —  NOT IMPLEMENTED YET             │
 * │                                                          │
 * │  When the Gemini API key is configured, this route will: │
 * │  1. Receive raw HeritageLead data (JSON body)            │
 * │  2. Call Gemini 1.5 Flash with a structured-output       │
 * │     prompt using response_schema                         │
 * │  3. Return a structured Heritage Record JSON:            │
 * │     {                                                     │
 * │       historicalContext: string,                         │
 * │       tradition:         string,                         │
 * │       evidence:          string[],                       │
 * │       sources:           string[],                       │
 * │       suggestedTitle:    string,                         │
 * │       keyFigures:        string[],                       │
 * │       timePeriod:        string,                         │
 * │     }                                                     │
 * └──────────────────────────────────────────────────────────┘
 *
 * For now this route returns a static mock response so the UI
 * can be built and tested end-to-end without a live API key.
 */

import { NextRequest, NextResponse } from 'next/server';

export interface StructuredHeritageRecord {
  suggestedTitle: string;
  historicalContext: string;
  tradition: string;
  evidence: string[];
  sources: string[];
  keyFigures: string[];
  timePeriod: string;
  _isAiGenerated: boolean;
  _isPlaceholder: boolean;
}

export async function POST(req: NextRequest) {
  // ── Guard: check for Gemini API key ────────────────────────────────────────
  const apiKey = process.env.GEMINI_API_KEY;

  if (!apiKey) {
    // ── Return placeholder mock response ─────────────────────────────────────
    //    Remove this block and implement Gemini call below once key is set.
    const body = await req.json().catch(() => ({}));
    const name   = (body?.name   as string) ?? 'this heritage site';
    const desc   = (body?.description as string) ?? '';
    const lang   = (body?.language as string) ?? 'English';

    const mockResponse: StructuredHeritageRecord = {
      suggestedTitle: `Heritage Record: ${name}`,
      historicalContext:
        `[AI Placeholder] This section will be auto-generated by Gemini 1.5 Flash. `
        + `It will provide a structured historical context based on the submitted description: "${desc.slice(0, 120)}..."`,
      tradition:
        `[AI Placeholder] Oral traditions and cultural practices associated with ${name} `
        + `will be extracted and summarised from the community submission.`,
      evidence: [
        '[AI Placeholder] Photographic evidence review will appear here.',
        '[AI Placeholder] Document cross-references will be listed here.',
      ],
      sources: [
        '[AI Placeholder] Source 1 — will be extracted from supportingEvidence field.',
        '[AI Placeholder] Source 2 — will be generated based on known heritage databases.',
      ],
      keyFigures: ['[AI Placeholder] Historical figures will be identified by the AI model.'],
      timePeriod: '[AI Placeholder] Approximate historical period will be determined by AI.',
      _isAiGenerated: false,
      _isPlaceholder: true,
    };

    return NextResponse.json(
      {
        success: true,
        data: mockResponse,
        message: `AI documentation not available yet. Configure GEMINI_API_KEY to enable. Language requested: ${lang}.`,
      },
      { status: 200 },
    );
  }

  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  // 🤖 TODO: Implement Gemini API call here
  //
  // const { GoogleGenerativeAI, SchemaType } = await import('@google/generative-ai');
  // const genAI = new GoogleGenerativeAI(apiKey);
  // const model = genAI.getGenerativeModel({
  //   model: 'gemini-1.5-flash',
  //   generationConfig: {
  //     responseMimeType: 'application/json',
  //     responseSchema: { ... },
  //   },
  // });
  // const body = await req.json();
  // const prompt = buildDocumentationPrompt(body);
  // const result = await model.generateContent(prompt);
  // const structured = JSON.parse(result.response.text());
  // return NextResponse.json({ success: true, data: { ...structured, _isAiGenerated: true, _isPlaceholder: false } });
  // ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  return NextResponse.json(
    { success: false, message: 'AI implementation pending.' },
    { status: 501 },
  );
}
